name = "newsnow"
pages_build_output_dir = "dist/output/public"
compatibility_date = "2024-10-03"

[[d1_databases]]
binding = "NEWSNOW_DB"
database_name = "new"
database_id = "189fec2b-6e36-43b1-ba49-3577de014dc8"
